server:
  port: 8060
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# 파일 리턴 기본 경로 : src/main/resources/static => 정적인 파일들을 모아두는곳(html, png,jpg…)
# src/main/webapp/WEB-INF/views => 동적인 파일들을 모아두는 곳(jsp) ---- src/main 밑에 webapp/WEB-INF/views 폴더를 생성

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul
    username: insta
    password: insta

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        use-new-id-generator-mappings: false
    show-sql: true
#    properties:
#      hibernate.enable_lazy_load_no_trans: true
#      hibernate.format_sql: true
      
  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
            
  security:
    user:
      name: test
      password: 1234

file:
  path: /home/sundor/workspace/spring4/insta/src/main/resources/upload/
 